/**
 * Firebase Configuration & Initialization for Filterer.
 *
 * Uses Firebase Firestore for:
 * - Stock detail data (fetched on demand when user opens /stock/:symbol)
 * - Market index data (updated by the Python pipeline)
 *
 * The Firebase config below is public (client-side) - security is enforced
 * by Firestore Security Rules (read-only for clients).
 */

import type { Firestore } from 'firebase/firestore';
import type { Stock } from '../types/stock';
import { normalizeRemoteStock } from './normalizeStock';

/**
 * Filesystem- and URL-safe name for a company's detail file, matching
 * scripts/split_dataset.mjs. Symbols such as M&M cannot be used raw: the old
 * code fetched /data/stocks/M&M.json while the file on disk was M%26M.json,
 * so that company's statements never loaded.
 */
export function detailSlug(symbol: string): string {
  return symbol.toUpperCase().replace(/[^A-Z0-9]+/g, '_');
}

const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY || '',
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || 'filterer-68dd0.firebaseapp.com',
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || 'filterer-68dd0',
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || 'filterer-68dd0.firebasestorage.app',
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '587965525417',
  appId: import.meta.env.VITE_FIREBASE_APP_ID || '',
  measurementId: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID || ''
};

// Firestore is optional: without credentials the app runs entirely off the
// static JSON tier. The SDK is 530 kB, so it is imported on demand rather than
// pulled into the entry chunk for a page most visitors never open.
const isConfigured = Boolean(firebaseConfig.apiKey && firebaseConfig.projectId);

let firestorePromise: Promise<Firestore | null> | null = null;

async function getDb(): Promise<Firestore | null> {
  if (!isConfigured) return null;
  if (!firestorePromise) {
    firestorePromise = (async () => {
      try {
        const [{ initializeApp }, { getFirestore }] = await Promise.all([
          import('firebase/app'),
          import('firebase/firestore'),
        ]);
        return getFirestore(initializeApp(firebaseConfig));
      } catch (err) {
        console.warn('Firebase unavailable; using the static JSON tier instead:', err);
        return null;
      }
    })();
  }
  return firestorePromise;
}

// ────────────────────────────────────────────────────────
//  FIRESTORE DATA ACCESS
// ────────────────────────────────────────────────────────

/**
 * Fetch full stock detail data from Firestore.
 * Used by the StockDetailPage when a user navigates to /stock/:symbol.
 *
 * Falls back to static JSON if Firestore is unavailable or unconfigured.
 */
export async function fetchStockDetail(symbol: string): Promise<Partial<Stock> | null> {
  const db = await getDb();
  if (!db) {
    return await fetchStockDetailFromJSON(symbol);
  }

  try {
    const { doc, getDoc } = await import('firebase/firestore');
    const docRef = doc(db, 'stocks', symbol.toUpperCase());
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
      // Runtime statements get the same treatment as the bundled ones, so a
      // fetched copy cannot reintroduce zeros where a figure was never
      // reported. See src/lib/normalizeStock.ts.
      return normalizeRemoteStock(docSnap.data() as Partial<Stock>);
    }

    // Fallback: try static JSON file
    return await fetchStockDetailFromJSON(symbol);
  } catch (error) {
    console.warn(`Firestore fetch failed for ${symbol}, falling back to static JSON:`, error);
    return await fetchStockDetailFromJSON(symbol);
  }
}

/**
 * Fallback: fetch stock detail from static JSON file.
 * These are generated by the Python pipeline into public/data/stocks/.
 */
async function fetchStockDetailFromJSON(symbol: string): Promise<Partial<Stock> | null> {
  try {
    const response = await fetch(`/data/stocks/${detailSlug(symbol)}.json`);
    if (!response.ok) return null;

    // A misconfigured SPA rewrite answers a missing file with index.html and
    // a 200, so `ok` is not enough to trust the body.
    const contentType = response.headers.get('content-type') || '';
    if (!contentType.includes('json')) {
      console.warn(`Expected JSON for ${symbol}, got ${contentType || 'no content-type'}. ` +
        'The static data files are probably missing from this deployment.');
      return null;
    }
    return normalizeRemoteStock((await response.json()) as Partial<Stock>);
  } catch {
    return null;
  }
}

/**
 * Fetch market indices data from Firestore.
 * Falls back to static JSON cache.
 */
export interface MarketIndex {
  id: string;
  symbol: string;
  name: string;
  exchange: string;
  price: number;
  change: number;
  changePct: number;
  previousClose: number;
  dayHigh: number;
  dayLow: number;
  high52w: number;
  low52w: number;
}

export interface MarketIndicesCache {
  indices: MarketIndex[];
  lastUpdated: string;
}

export async function fetchMarketIndices(): Promise<MarketIndicesCache | null> {
  const db = await getDb();
  if (!db) {
    return await fetchMarketIndicesFromJSON();
  }

  try {
    const { doc, getDoc } = await import('firebase/firestore');
    const docRef = doc(db, 'market', 'indices');
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
      return docSnap.data() as MarketIndicesCache;
    }

    // Fallback to static JSON
    return await fetchMarketIndicesFromJSON();
  } catch (error) {
    console.warn('Firestore indices fetch failed, falling back to static JSON:', error);
    return await fetchMarketIndicesFromJSON();
  }
}

async function fetchMarketIndicesFromJSON(): Promise<MarketIndicesCache | null> {
  try {
    const response = await fetch('/data/market_indices.json');
    if (!response.ok) return null;
    return await response.json();
  } catch {
    return null;
  }
}
