/**
 * Firebase Configuration & Initialization for Filterer.
 *
 * Uses Firebase Firestore for:
 * - Stock detail data (fetched on demand when user opens /stock/:symbol)
 * - Market index data (updated by the Python pipeline)
 *
 * The Firebase config below is public (client-side) — security is enforced
 * by Firestore Security Rules (read-only for clients).
 */

import { initializeApp } from 'firebase/app';
import { getFirestore, doc, getDoc, collection, getDocs, query, where, DocumentData } from 'firebase/firestore';
import type { Stock } from '../types/stock';

const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY || '',
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || 'filterer-68dd0.firebaseapp.com',
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || 'filterer-68dd0',
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || 'filterer-68dd0.firebasestorage.app',
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '587965525417',
  appId: import.meta.env.VITE_FIREBASE_APP_ID || '',
  measurementId: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID || ''
};

// Initialize Firebase conditionally if client credentials are provided
const isConfigured = Boolean(firebaseConfig.apiKey && firebaseConfig.projectId);

export const db = isConfigured
  ? (() => {
      try {
        const app = initializeApp(firebaseConfig);
        return getFirestore(app);
      } catch (err) {
        console.warn('Firebase initialization failed; using static JSON fallback:', err);
        return null;
      }
    })()
  : null;

// ────────────────────────────────────────────────────────
//  FIRESTORE DATA ACCESS
// ────────────────────────────────────────────────────────

/**
 * Fetch full stock detail data from Firestore.
 * Used by the StockDetailPage when a user navigates to /stock/:symbol.
 *
 * Falls back to static JSON if Firestore is unavailable or unconfigured.
 */
export async function fetchStockDetail(symbol: string): Promise<Partial<Stock> | null> {
  if (!db) {
    return await fetchStockDetailFromJSON(symbol);
  }

  try {
    const docRef = doc(db, 'stocks', symbol.toUpperCase());
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
      return docSnap.data() as Partial<Stock>;
    }

    // Fallback: try static JSON file
    return await fetchStockDetailFromJSON(symbol);
  } catch (error) {
    console.warn(`Firestore fetch failed for ${symbol}, falling back to static JSON:`, error);
    return await fetchStockDetailFromJSON(symbol);
  }
}

/**
 * Fallback: fetch stock detail from static JSON file.
 * These are generated by the Python pipeline into public/data/stocks/.
 */
async function fetchStockDetailFromJSON(symbol: string): Promise<Partial<Stock> | null> {
  try {
    const response = await fetch(`/data/stocks/${symbol.toUpperCase()}.json`);
    if (!response.ok) return null;
    return await response.json();
  } catch {
    return null;
  }
}

/**
 * Fetch market indices data from Firestore.
 * Falls back to static JSON cache.
 */
export interface MarketIndex {
  id: string;
  symbol: string;
  name: string;
  exchange: string;
  price: number;
  change: number;
  changePct: number;
  previousClose: number;
  dayHigh: number;
  dayLow: number;
  high52w: number;
  low52w: number;
}

export interface MarketIndicesCache {
  indices: MarketIndex[];
  lastUpdated: string;
}

export async function fetchMarketIndices(): Promise<MarketIndicesCache | null> {
  if (!db) {
    return await fetchMarketIndicesFromJSON();
  }

  try {
    // Try Firestore first
    const docRef = doc(db, 'market', 'indices');
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
      return docSnap.data() as MarketIndicesCache;
    }

    // Fallback to static JSON
    return await fetchMarketIndicesFromJSON();
  } catch (error) {
    console.warn('Firestore indices fetch failed, falling back to static JSON:', error);
    return await fetchMarketIndicesFromJSON();
  }
}

async function fetchMarketIndicesFromJSON(): Promise<MarketIndicesCache | null> {
  try {
    const response = await fetch('/data/market_indices.json');
    if (!response.ok) return null;
    return await response.json();
  } catch {
    return null;
  }
}
