/**
 * Firebase Configuration & Initialization for Filterer.
 *
 * Uses Firebase Firestore for:
 * - Stock detail data (fetched on demand when user opens /stock/:symbol)
 * - Market index data (updated by the Python pipeline)
 *
 * The Firebase config below is public (client-side) — security is enforced
 * by Firestore Security Rules (read-only for clients).
 */

import { initializeApp } from 'firebase/app';
import { getFirestore, doc, getDoc, collection, getDocs, query, where, DocumentData } from 'firebase/firestore';
import type { Stock } from '../types/stock';

const firebaseConfig = {
  apiKey: "AIzaSyCfSd8RlEyfPrOYZ3NZSxx3JfY_yJOi5ys",
  authDomain: "filterer-68dd0.firebaseapp.com",
  projectId: "filterer-68dd0",
  storageBucket: "filterer-68dd0.firebasestorage.app",
  messagingSenderId: "587965525417",
  appId: "1:587965525417:web:2a48c119f515d51f44a8b8",
  measurementId: "G-V52102N1E9"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
export const db = getFirestore(app);

// ────────────────────────────────────────────────────────
//  FIRESTORE DATA ACCESS
// ────────────────────────────────────────────────────────

/**
 * Fetch full stock detail data from Firestore.
 * Used by the StockDetailPage when a user navigates to /stock/:symbol.
 *
 * Falls back to static JSON if Firestore is unavailable.
 */
export async function fetchStockDetail(symbol: string): Promise<Partial<Stock> | null> {
  try {
    const docRef = doc(db, 'stocks', symbol.toUpperCase());
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
      return docSnap.data() as Partial<Stock>;
    }

    // Fallback: try static JSON file
    return await fetchStockDetailFromJSON(symbol);
  } catch (error) {
    console.warn(`Firestore fetch failed for ${symbol}, falling back to static JSON:`, error);
    return await fetchStockDetailFromJSON(symbol);
  }
}

/**
 * Fallback: fetch stock detail from static JSON file.
 * These are generated by the Python pipeline into public/data/stocks/.
 */
async function fetchStockDetailFromJSON(symbol: string): Promise<Partial<Stock> | null> {
  try {
    const response = await fetch(`/data/stocks/${symbol.toUpperCase()}.json`);
    if (!response.ok) return null;
    return await response.json();
  } catch {
    return null;
  }
}

/**
 * Fetch market indices data from Firestore.
 * Falls back to static JSON cache.
 */
export interface MarketIndex {
  id: string;
  symbol: string;
  name: string;
  exchange: string;
  price: number;
  change: number;
  changePct: number;
  previousClose: number;
  dayHigh: number;
  dayLow: number;
  high52w: number;
  low52w: number;
}

export interface MarketIndicesCache {
  indices: MarketIndex[];
  lastUpdated: string;
}

export async function fetchMarketIndices(): Promise<MarketIndicesCache | null> {
  try {
    // Try Firestore first
    const docRef = doc(db, 'market', 'indices');
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
      return docSnap.data() as MarketIndicesCache;
    }

    // Fallback to static JSON
    return await fetchMarketIndicesFromJSON();
  } catch (error) {
    console.warn('Firestore indices fetch failed, falling back to static JSON:', error);
    return await fetchMarketIndicesFromJSON();
  }
}

async function fetchMarketIndicesFromJSON(): Promise<MarketIndicesCache | null> {
  try {
    const response = await fetch('/data/market_indices.json');
    if (!response.ok) return null;
    return await response.json();
  } catch {
    return null;
  }
}
