/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        apple: {
          DEFAULT: 'var(--apple-border)',
          bg: 'var(--apple-bg)',
          subtle: 'var(--apple-bg-subtle)',
          tertiary: 'var(--apple-bg-tertiary)',
          surface: 'var(--apple-surface)',
          'surface-hover': 'var(--apple-surface-hover)',
          'surface-active': 'var(--apple-surface-active)',
          card: 'var(--apple-card-bg)',
          raised: 'var(--apple-card-raised)',
          border: 'var(--apple-border)',
          'border-subtle': 'var(--apple-border-subtle)',
          'border-strong': 'var(--apple-border-strong)',
          primary: 'var(--apple-text-primary)',
          label: 'var(--apple-text-primary)',
          secondary: 'var(--apple-text-secondary)',
          muted: 'var(--apple-text-muted)',
          faint: 'var(--apple-text-faint)',
          blue: 'var(--apple-blue)',
          'blue-subtle': 'var(--apple-blue-subtle)',
          green: 'var(--apple-green)',
          'green-subtle': 'var(--apple-green-subtle)',
          red: 'var(--apple-red)',
          'red-subtle': 'var(--apple-red-subtle)',
          amber: 'var(--apple-amber)',
          'amber-subtle': 'var(--apple-amber-subtle)',
          indigo: 'var(--apple-indigo)',
          'indigo-subtle': 'var(--apple-indigo-subtle)',
        },
      },
      boxShadow: {
        xs: 'var(--apple-shadow-sm)',
        sm: 'var(--apple-shadow-sm)',
        DEFAULT: 'var(--apple-shadow)',
        lg: 'var(--apple-shadow-lg)',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Text"',
          '"SF Pro Display"',
          '"Plus Jakarta Sans"',
          'Inter',
          'system-ui',
          'sans-serif',
        ],
        display: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Display"',
          '"Plus Jakarta Sans"',
          'Inter',
          'system-ui',
          'sans-serif',
        ],
        mono: [
          '"SF Mono"',
          '"JetBrains Mono"',
          'ui-monospace',
          'Menlo',
          'Monaco',
          'Consolas',
          'monospace',
        ],
      },
    },
  },
  plugins: [],
};
