import type { VercelRequest, VercelResponse } from '@vercel/node';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

/**
 * Market Indices API Endpoint.
 * 
 * Reads from the cached market_indices.json generated by the Python pipeline,
 * or falls back to Firestore data. No more hardcoded prices.
 */

interface IndexData {
  id: string;
  symbol: string;
  name: string;
  exchange: string;
  price: number;
  change: number;
  changePct: number;
  previousClose: number;
  dayHigh: number;
  dayLow: number;
  high52w: number;
  low52w: number;
}

interface IndicesCache {
  indices: IndexData[];
  lastUpdated: string;
  source: string;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Cache-Control', 's-maxage=60, stale-while-revalidate=300');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // Calculate IST time and market status
  const now = new Date();
  const utc = now.getTime() + (now.getTimezoneOffset() * 60000);
  const istDate = new Date(utc + (3600000 * 5.5));
  
  const day = istDate.getDay();
  const hours = istDate.getHours();
  const minutes = istDate.getMinutes();
  const timeInMinutes = hours * 60 + minutes;
  
  // Market hours: 9:15 AM (555 mins) to 3:30 PM (930 mins) on Mon-Fri
  const isMarketOpen = day >= 1 && day <= 5 && timeInMinutes >= 555 && timeInMinutes <= 930;

  try {
    // Try to read cached indices from the pipeline-generated JSON
    const cachePath = join(process.cwd(), 'data', 'market_indices.json');
    let indicesData: IndicesCache | null = null;

    if (existsSync(cachePath)) {
      const raw = readFileSync(cachePath, 'utf-8');
      indicesData = JSON.parse(raw) as IndicesCache;
    }

    // Format for the frontend
    const indices = (indicesData?.indices || []).map((idx) => ({
      symbol: idx.symbol,
      name: idx.name,
      price: idx.price,
      change: idx.change,
      change_pct: idx.changePct,
      is_up: idx.change >= 0,
    }));

    return res.status(200).json({
      status: 'ok',
      is_market_open: isMarketOpen,
      time_ist: istDate.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: true }) + ' IST',
      date_ist: istDate.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }),
      last_updated: indicesData?.lastUpdated || 'unknown',
      source: indicesData?.source || 'cache',
      indices,
    });
  } catch (error: any) {
    return res.status(500).json({
      status: 'error',
      message: error.message || 'Error fetching market indices',
    });
  }
}
