"""
Filterer Stock Universe (Nifty 500).

Canonical listing of the 500 constituents of the Nifty 500 index on the
National Stock Exchange of India (NSE). Sourced directly from official NSE
index records, structured by sector and industry for quantitative screening.

All entries map to valid NSE tickers. For Yahoo Finance integration, the
symbol is automatically appended with ".NS" (or resolved via TICKER_ALIASES).
"""

from typing import Dict, List, Tuple

# Official NSE Nifty 500 Master Universe (500 Constituents)
# Format: (NSE_SYMBOL, COMPANY_NAME)
STOCK_UNIVERSE: List[Tuple[str, str]] = [
    # ──────────────────── AUTOMOBILE AND AUTO COMPONENTS (38) ────────────────────
    ("APOLLOTYRE", "Apollo Tyres Ltd."),
    ("ARE&M", "Amara Raja Energy & Mobility Ltd."),
    ("ASAHIINDIA", "Asahi India Glass Ltd."),
    ("ATHERENERG", "Ather Energy Ltd."),
    ("BAJAJ-AUTO", "Bajaj Auto Ltd."),
    ("BALKRISIND", "Balkrishna Industries Ltd."),
    ("BELRISE", "Belrise Industries Ltd."),
    ("BHARATFORG", "Bharat Forge Ltd."),
    ("BOSCHLTD", "Bosch Ltd."),
    ("CEATLTD", "Ceat Ltd."),
    ("CIEINDIA", "CIE Automotive India Ltd."),
    ("CRAFTSMAN", "Craftsman Automation Ltd."),
    ("EICHERMOT", "Eicher Motors Ltd."),
    ("ENDURANCE", "Endurance Technologies Ltd."),
    ("EXIDEIND", "Exide Industries Ltd."),
    ("FORCEMOT", "Force Motors Ltd."),
    ("GABRIEL", "Gabriel India Ltd."),
    ("HEROMOTOCO", "Hero MotoCorp Ltd."),
    ("HYUNDAI", "Hyundai Motor India Ltd."),
    ("JBMA", "JBM Auto Ltd."),
    ("JKTYRE", "JK Tyre & Industries Ltd."),
    ("M&M", "Mahindra & Mahindra Ltd."),
    ("MARUTI", "Maruti Suzuki India Ltd."),
    ("MINDACORP", "Minda Corporation Ltd."),
    ("MOTHERSON", "Samvardhana Motherson International Ltd."),
    ("MRF", "MRF Ltd."),
    ("MSUMI", "Motherson Sumi Wiring India Ltd."),
    ("OLAELEC", "Ola Electric Mobility Ltd."),
    ("OLECTRA", "Olectra Greentech Ltd."),
    ("RKFORGE", "Ramkrishna Forgings Ltd."),
    ("SCHAEFFLER", "Schaeffler India Ltd."),
    ("SONACOMS", "Sona BLW Precision Forgings Ltd."),
    ("TENNIND", "Tenneco Clean Air India Ltd."),
    ("TIINDIA", "Tube Investments of India Ltd."),
    ("TMPV", "Tata Motors Passenger Vehicles Ltd."),
    ("TVSMOTOR", "TVS Motor Company Ltd."),
    ("UNOMINDA", "UNO Minda Ltd."),
    ("ZFCVINDIA", "ZF Commercial Vehicle Control Systems India Ltd."),
    # ──────────────────── CAPITAL GOODS (63) ────────────────────
    ("ABB", "ABB India Ltd."),
    ("ACE", "Action Construction Equipment Ltd."),
    ("AIAENG", "AIA Engineering Ltd."),
    ("APARINDS", "Apar Industries Ltd."),
    ("APLAPOLLO", "APL Apollo Tubes Ltd."),
    ("ASHOKLEY", "Ashok Leyland Ltd."),
    ("ASTRAL", "Astral Ltd."),
    ("BDL", "Bharat Dynamics Ltd."),
    ("BEL", "Bharat Electronics Ltd."),
    ("BEML", "BEML Ltd."),
    ("BHEL", "Bharat Heavy Electricals Ltd."),
    ("CARBORUNIV", "Carborundum Universal Ltd."),
    ("CGPOWER", "CG Power and Industrial Solutions Ltd."),
    ("COCHINSHIP", "Cochin Shipyard Ltd."),
    ("CPPLUS", "Aditya Infotech Ltd."),
    ("CUMMINSIND", "Cummins India Ltd."),
    ("DATAPATTNS", "Data Patterns (India) Ltd."),
    ("ELECON", "Elecon Engineering Co. Ltd."),
    ("ELGIEQUIP", "Elgi Equipments Ltd."),
    ("EMMVEE", "Emmvee Photovoltaic Power Ltd."),
    ("ENRIN", "Siemens Energy India Ltd."),
    ("ESCORTS", "Escorts Kubota Ltd."),
    ("FINCABLES", "Finolex Cables Ltd."),
    ("GALLANTT", "Gallantt Ispat Ltd."),
    ("GPIL", "Godawari Power & Ispat Ltd."),
    ("GRAPHITE", "Graphite India Ltd."),
    ("GRSE", "Garden Reach Shipbuilders & Engineers Ltd."),
    ("GVT&D", "GE Vernova T&D India Ltd."),
    ("HAL", "Hindustan Aeronautics Ltd."),
    ("HBLENGINE", "HBL Engineering Ltd."),
    ("HEG", "H.E.G. Ltd."),
    ("HONAUT", "Honeywell Automation India Ltd."),
    ("INOXWIND", "Inox Wind Ltd."),
    ("JINDALSAW", "Jindal Saw Ltd."),
    ("JWL", "Jupiter Wagons Ltd."),
    ("JYOTICNC", "Jyoti CNC Automation Ltd."),
    ("KAYNES", "Kaynes Technology India Ltd."),
    ("KEI", "KEI Industries Ltd."),
    ("KIRLOSENG", "Kirloskar Oil Eng Ltd."),
    ("MAZDOCK", "Mazagoan Dock Shipbuilders Ltd."),
    ("POLYCAB", "Polycab India Ltd."),
    ("POWERINDIA", "Hitachi Energy India Ltd."),
    ("PREMIERENE", "Premier Energies Ltd."),
    ("PTCIL", "PTC Industries Ltd."),
    ("RHIM", "RHI MAGNESITA INDIA LTD."),
    ("RRKABEL", "R R Kabel Ltd."),
    ("SCHNEIDER", "Schneider Electric Infrastructure Ltd."),
    ("SHYAMMETL", "Shyam Metalics and Energy Ltd."),
    ("SIEMENS", "Siemens Ltd."),
    ("SUPREMEIND", "Supreme Industries Ltd."),
    ("SUZLON", "Suzlon Energy Ltd."),
    ("SYRMA", "Syrma SGS Technology Ltd."),
    ("TARIL", "Transformers And Rectifiers (India) Ltd."),
    ("TEGA", "Tega Industries Ltd."),
    ("THERMAX", "Thermax Ltd."),
    ("TIMKEN", "Timken India Ltd."),
    ("TITAGARH", "Titagarh Rail Systems Ltd."),
    ("TMCV", "Tata Motors Ltd."),
    ("TRITURBINE", "Triveni Turbine Ltd."),
    ("USHAMART", "Usha Martin Ltd."),
    ("WAAREEENER", "Waaree Energies Ltd."),
    ("WELCORP", "Welspun Corp Ltd."),
    ("ZENTEC", "Zen Technologies Ltd."),
    # ──────────────────── CHEMICALS (26) ────────────────────
    ("AARTIIND", "Aarti Industries Ltd."),
    ("ANURAS", "Anupam Rasayan India Ltd."),
    ("ATUL", "Atul Ltd."),
    ("BAYERCROP", "Bayer Cropscience Ltd."),
    ("CHAMBLFERT", "Chambal Fertilizers & Chemicals Ltd."),
    ("CLEAN", "Clean Science and Technology Ltd."),
    ("COROMANDEL", "Coromandel International Ltd."),
    ("DEEPAKFERT", "Deepak Fertilisers & Petrochemicals Corp. Ltd."),
    ("DEEPAKNTR", "Deepak Nitrite Ltd."),
    ("FACT", "Fertilisers and Chemicals Travancore Ltd."),
    ("FLUOROCHEM", "Gujarat Fluorochemicals Ltd."),
    ("HSCL", "Himadri Speciality Chemical Ltd."),
    ("JUBLINGREA", "Jubilant Ingrevia Ltd."),
    ("LINDEINDIA", "Linde India Ltd."),
    ("NAVINFLUOR", "Navin Fluorine International Ltd."),
    ("PARADEEP", "Paradeep Phosphates Ltd."),
    ("PCBL", "PCBL Chemical Ltd."),
    ("PIDILITIND", "Pidilite Industries Ltd."),
    ("PIIND", "PI Industries Ltd."),
    ("SOLARINDS", "Solar Industries India Ltd."),
    ("SPLPETRO", "Supreme Petrochem Ltd."),
    ("SRF", "SRF Ltd."),
    ("SUMICHEM", "Sumitomo Chemical India Ltd."),
    ("SWANCORP", "Swan Corp Ltd."),
    ("TATACHEM", "Tata Chemicals Ltd."),
    ("UPL", "UPL Ltd."),
    # ──────────────────── CONSTRUCTION (13) ────────────────────
    ("AFCONS", "Afcons Infrastructure Ltd."),
    ("CEMPRO", "Cemindia Projects Ltd."),
    ("ENGINERSIN", "Engineers India Ltd."),
    ("IRB", "IRB Infrastructure Developers Ltd."),
    ("IRCON", "IRCON International Ltd."),
    ("KEC", "Kec International Ltd."),
    ("KPIL", "Kalpataru Projects International Ltd."),
    ("LT", "Larsen & Toubro Ltd."),
    ("NBCC", "NBCC (India) Ltd."),
    ("NCC", "NCC Ltd."),
    ("RITES", "RITES Ltd."),
    ("RVNL", "Rail Vikas Nigam Ltd."),
    ("TECHNOE", "Techno Electric & Engineering Company Ltd."),
    # ──────────────────── CONSTRUCTION MATERIALS (11) ────────────────────
    ("ACC", "ACC Ltd."),
    ("AMBUJACEM", "Ambuja Cements Ltd."),
    ("DALBHARAT", "Dalmia Bharat Ltd."),
    ("GRASIM", "Grasim Industries Ltd."),
    ("INDIACEM", "India Cements Ltd."),
    ("JKCEMENT", "J.K. Cement Ltd."),
    ("JSWCEMENT", "JSW Cement Ltd."),
    ("NUVOCO", "Nuvoco Vistas Corporation Ltd."),
    ("RAMCOCEM", "The Ramco Cements Ltd."),
    ("SHREECEM", "Shree Cement Ltd."),
    ("ULTRACEMCO", "UltraTech Cement Ltd."),
    # ──────────────────── CONSUMER DURABLES (16) ────────────────────
    ("AMBER", "Amber Enterprises India Ltd."),
    ("ASIANPAINT", "Asian Paints Ltd."),
    ("BATAINDIA", "Bata India Ltd."),
    ("BERGEPAINT", "Berger Paints India Ltd."),
    ("BLUESTARCO", "Blue Star Ltd."),
    ("CROMPTON", "Crompton Greaves Consumer Electricals Ltd."),
    ("DIXON", "Dixon Technologies (India) Ltd."),
    ("HAVELLS", "Havells India Ltd."),
    ("JSWDULUX", "JSW Dulux Ltd."),
    ("KAJARIACER", "Kajaria Ceramics Ltd."),
    ("KALYANKJIL", "Kalyan Jewellers India Ltd."),
    ("LGEINDIA", "LG Electronics India Ltd."),
    ("PGEL", "PG Electroplast Ltd."),
    ("TITAN", "Titan Company Ltd."),
    ("VOLTAS", "Voltas Ltd."),
    ("WHIRLPOOL", "Whirlpool of India Ltd."),
    # ──────────────────── CONSUMER SERVICES (29) ────────────────────
    ("ABFRL", "Aditya Birla Fashion and Retail Ltd."),
    ("ABLBL", "Aditya Birla Lifestyle Brands Ltd."),
    ("BLS", "BLS International Services Ltd."),
    ("CARTRADE", "Cartrade Tech Ltd."),
    ("CHALET", "Chalet Hotels Ltd."),
    ("DEVYANI", "Devyani International Ltd."),
    ("DMART", "Avenue Supermarts Ltd."),
    ("EIHOTEL", "EIH Ltd."),
    ("ETERNAL", "Eternal Ltd."),
    ("FIRSTCRY", "Brainbees Solutions Ltd."),
    ("INDHOTEL", "Indian Hotels Co. Ltd."),
    ("INDIAMART", "Indiamart Intermesh Ltd."),
    ("IRCTC", "Indian Railway Catering And Tourism Corporation Ltd."),
    ("ITCHOTELS", "ITC Hotels Ltd."),
    ("JUBLFOOD", "Jubilant Foodworks Ltd."),
    ("LEMONTREE", "Lemon Tree Hotels Ltd."),
    ("LENSKART", "Lenskart Solutions Ltd."),
    ("MEESHO", "Meesho Ltd."),
    ("NAUKRI", "Info Edge (India) Ltd."),
    ("NYKAA", "FSN E-Commerce Ventures Ltd."),
    ("PWL", "Physicswallah Ltd."),
    ("SAPPHIRE", "Sapphire Foods India Ltd."),
    ("SWIGGY", "Swiggy Ltd."),
    ("TBOTEK", "TBO Tek Ltd."),
    ("THELEELA", "Leela Palaces Hotels & Resorts Ltd."),
    ("TRAVELFOOD", "Travel Food Services Ltd."),
    ("TRENT", "Trent Ltd."),
    ("URBANCO", "Urban Company Ltd."),
    ("VMM", "Vishal Mega Mart Ltd."),
    # ──────────────────── DIVERSIFIED (3) ────────────────────
    ("3MINDIA", "3M India Ltd."),
    ("DCMSHRIRAM", "DCM Shriram Ltd."),
    ("GODREJIND", "Godrej Industries Ltd."),
    # ──────────────────── FAST MOVING CONSUMER GOODS (28) ────────────────────
    ("ABDL", "Allied Blenders and Distillers Ltd."),
    ("AWL", "AWL Agri Business Ltd."),
    ("BALRAMCHIN", "Balrampur Chini Mills Ltd."),
    ("BBTC", "Bombay Burmah Trading Corporation Ltd."),
    ("BIKAJI", "Bikaji Foods International Ltd."),
    ("BRITANNIA", "Britannia Industries Ltd."),
    ("CCL", "CCL Products (I) Ltd."),
    ("COLPAL", "Colgate Palmolive (India) Ltd."),
    ("DABUR", "Dabur India Ltd."),
    ("DOMS", "DOMS Industries Ltd."),
    ("EIDPARRY", "E.I.D. Parry (India) Ltd."),
    ("EMAMILTD", "Emami Ltd."),
    ("GILLETTE", "Gillette India Ltd."),
    ("GODFRYPHLP", "Godfrey Phillips India Ltd."),
    ("GODREJCP", "Godrej Consumer Products Ltd."),
    ("HINDUNILVR", "Hindustan Unilever Ltd."),
    ("HONASA", "Honasa Consumer Ltd."),
    ("ITC", "ITC Ltd."),
    ("LTFOODS", "LT Foods Ltd."),
    ("MARICO", "Marico Ltd."),
    ("NESTLEIND", "Nestle India Ltd."),
    ("PATANJALI", "Patanjali Foods Ltd."),
    ("RADICO", "Radico Khaitan Ltd"),
    ("TATACONSUM", "Tata Consumer Products Ltd."),
    ("UBL", "United Breweries Ltd."),
    ("UNITDSPR", "United Spirits Ltd."),
    ("VBL", "Varun Beverages Ltd."),
    ("ZYDUSWELL", "Zydus Wellness Ltd."),
    # ──────────────────── FINANCIAL SERVICES (101) ────────────────────
    ("360ONE", "360 ONE WAM Ltd."),
    ("AADHARHFC", "Aadhar Housing Finance Ltd."),
    ("AAVAS", "Aavas Financiers Ltd."),
    ("ABCAPITAL", "Aditya Birla Capital Ltd."),
    ("ABSLAMC", "Aditya Birla Sun Life AMC Ltd."),
    ("AIIL", "Authum Investment & Infrastructure Ltd."),
    ("ANANDRATHI", "Anand Rathi Wealth Ltd."),
    ("ANGELONE", "Angel One Ltd."),
    ("APTUS", "Aptus Value Housing Finance India Ltd."),
    ("AUBANK", "AU Small Finance Bank Ltd."),
    ("AXISBANK", "Axis Bank Ltd."),
    ("BAJAJFINSV", "Bajaj Finserv Ltd."),
    ("BAJAJHFL", "Bajaj Housing Finance Ltd."),
    ("BAJAJHLDNG", "Bajaj Holdings & Investment Ltd."),
    ("BAJFINANCE", "Bajaj Finance Ltd."),
    ("BANDHANBNK", "Bandhan Bank Ltd."),
    ("BANKBARODA", "Bank of Baroda"),
    ("BANKINDIA", "Bank of India"),
    ("BSE", "BSE Ltd."),
    ("CAMS", "Computer Age Management Services Ltd."),
    ("CANBK", "Canara Bank"),
    ("CANFINHOME", "Can Fin Homes Ltd."),
    ("CANHLIFE", "Canara HSBC Life Insurance Company Ltd."),
    ("CDSL", "Central Depository Services (India) Ltd."),
    ("CENTRALBK", "Central Bank of India"),
    ("CGCL", "Capri Global Capital Ltd."),
    ("CHOICEIN", "Choice International Ltd."),
    ("CHOLAFIN", "Cholamandalam Investment and Finance Company Ltd."),
    ("CHOLAHLDNG", "Cholamandalam Financial Holdings Ltd."),
    ("CREDITACC", "CreditAccess Grameen Ltd."),
    ("CRISIL", "CRISIL Ltd."),
    ("CUB", "City Union Bank Ltd."),
    ("FEDERALBNK", "Federal Bank Ltd."),
    ("FIVESTAR", "Five-Star Business Finance Ltd."),
    ("GICRE", "General Insurance Corporation of India"),
    ("GODIGIT", "Go Digit General Insurance Ltd."),
    ("GROWW", "Billionbrains Garage Ventures Ltd."),
    ("HDBFS", "HDB Financial Services Ltd."),
    ("HDFCAMC", "HDFC Asset Management Company Ltd."),
    ("HDFCBANK", "HDFC Bank Ltd."),
    ("HDFCLIFE", "HDFC Life Insurance Company Ltd."),
    ("HOMEFIRST", "Home First Finance Company India Ltd."),
    ("HUDCO", "Housing & Urban Development Corporation Ltd."),
    ("ICICIAMC", "ICICI Prudential Asset Management Company Ltd."),
    ("ICICIBANK", "ICICI Bank Ltd."),
    ("ICICIGI", "ICICI Lombard General Insurance Company Ltd."),
    ("ICICIPRULI", "ICICI Prudential Life Insurance Company Ltd."),
    ("IDBI", "IDBI Bank Ltd."),
    ("IDFCFIRSTB", "IDFC First Bank Ltd."),
    ("IEX", "Indian Energy Exchange Ltd."),
    ("IFCI", "IFCI Ltd."),
    ("IIFL", "IIFL Finance Ltd."),
    ("INDIANB", "Indian Bank"),
    ("INDUSINDBK", "IndusInd Bank Ltd."),
    ("IOB", "Indian Overseas Bank"),
    ("IREDA", "Indian Renewable Energy Development Agency Ltd."),
    ("IRFC", "Indian Railway Finance Corporation Ltd."),
    ("J&KBANK", "Jammu & Kashmir Bank Ltd."),
    ("JIOFIN", "Jio Financial Services Ltd."),
    ("JMFINANCIL", "JM Financial Ltd."),
    ("KARURVYSYA", "Karur Vysya Bank Ltd."),
    ("KFINTECH", "Kfin Technologies Ltd."),
    ("KOTAKBANK", "Kotak Mahindra Bank Ltd."),
    ("LICHSGFIN", "LIC Housing Finance Ltd."),
    ("LICI", "Life Insurance Corporation of India"),
    ("LTF", "L&T Finance Ltd."),
    ("M&MFIN", "Mahindra & Mahindra Financial Services Ltd."),
    ("MAHABANK", "Bank of Maharashtra"),
    ("MANAPPURAM", "Manappuram Finance Ltd."),
    ("MCX", "Multi Commodity Exchange of India Ltd."),
    ("MFSL", "Max Financial Services Ltd."),
    ("MOTILALOFS", "Motilal Oswal Financial Services Ltd."),
    ("MUTHOOTFIN", "Muthoot Finance Ltd."),
    ("NAM-INDIA", "Nippon Life India Asset Management Ltd."),
    ("NIACL", "The New India Assurance Company Ltd."),
    ("NIVABUPA", "Niva Bupa Health Insurance Company Ltd."),
    ("NUVAMA", "Nuvama Wealth Management Ltd."),
    ("PAYTM", "One 97 Communications Ltd."),
    ("PFC", "Power Finance Corporation Ltd."),
    ("PINELABS", "Pine Labs Ltd."),
    ("PIRAMALFIN", "Piramal Finance Ltd."),
    ("PNB", "Punjab National Bank"),
    ("PNBHOUSING", "PNB Housing Finance Ltd."),
    ("POLICYBZR", "PB Fintech Ltd."),
    ("POONAWALLA", "Poonawalla Fincorp Ltd."),
    ("RBLBANK", "RBL Bank Ltd."),
    ("RECLTD", "REC Ltd."),
    ("SAMMAANCAP", "Sammaan Capital Ltd."),
    ("SBFC", "SBFC Finance Ltd."),
    ("SBICARD", "SBI Cards and Payment Services Ltd."),
    ("SBILIFE", "SBI Life Insurance Company Ltd."),
    ("SBIN", "State Bank of India"),
    ("SHRIRAMFIN", "Shriram Finance Ltd."),
    ("STARHEALTH", "Star Health and Allied Insurance Company Ltd."),
    ("SUNDARMFIN", "Sundaram Finance Ltd."),
    ("TATACAP", "Tata Capital Ltd."),
    ("TATAINVEST", "Tata Investment Corporation Ltd."),
    ("UCOBANK", "UCO Bank"),
    ("UNIONBANK", "Union Bank of India"),
    ("UTIAMC", "UTI Asset Management Company Ltd."),
    ("YESBANK", "Yes Bank Ltd."),
    # ──────────────────── HEALTHCARE (48) ────────────────────
    ("ABBOTINDIA", "Abbott India Ltd."),
    ("ACUTAAS", "Acutaas Chemicals Ltd."),
    ("AJANTPHARM", "Ajanta Pharmaceuticals Ltd."),
    ("ALKEM", "Alkem Laboratories Ltd."),
    ("ANTHEM", "Anthem Biosciences Ltd."),
    ("APOLLOHOSP", "Apollo Hospitals Enterprise Ltd."),
    ("ASTERDM", "Aster DM Quality Care Ltd."),
    ("AUROPHARMA", "Aurobindo Pharma Ltd."),
    ("BIOCON", "Biocon Ltd."),
    ("BLUEJET", "Blue Jet Healthcare Ltd."),
    ("CAPLIPOINT", "Caplin Point Laboratories Ltd."),
    ("CIPLA", "Cipla Ltd."),
    ("COHANCE", "Cohance Lifesciences Ltd."),
    ("CONCORDBIO", "Concord Biotech Ltd."),
    ("DIVISLAB", "Divi's Laboratories Ltd."),
    ("DRREDDY", "Dr. Reddy's Laboratories Ltd."),
    ("EMCURE", "Emcure Pharmaceuticals Ltd."),
    ("ERIS", "Eris Lifesciences Ltd."),
    ("FORTIS", "Fortis Healthcare Ltd."),
    ("GLAND", "Gland Pharma Ltd."),
    ("GLAXO", "Glaxosmithkline Pharmaceuticals Ltd."),
    ("GLENMARK", "Glenmark Pharmaceuticals Ltd."),
    ("GRANULES", "Granules India Ltd."),
    ("INDGN", "Indegene Ltd."),
    ("IPCALAB", "Ipca Laboratories Ltd."),
    ("JUBLPHARMA", "Jubilant Pharmova Ltd."),
    ("KIMS", "Krishna Institute of Medical Sciences Ltd."),
    ("LALPATHLAB", "Dr. Lal Path Labs Ltd."),
    ("LAURUSLABS", "Laurus Labs Ltd."),
    ("LUPIN", "Lupin Ltd."),
    ("MANKIND", "Mankind Pharma Ltd."),
    ("MAXHEALTH", "Max Healthcare Institute Ltd."),
    ("MEDANTA", "Global Health Ltd."),
    ("NATCOPHARM", "NATCO Pharma Ltd."),
    ("NEULANDLAB", "Neuland Laboratories Ltd."),
    ("NH", "Narayana Hrudayalaya Ltd."),
    ("ONESOURCE", "Onesource Specialty Pharma Ltd."),
    ("PFIZER", "Pfizer Ltd."),
    ("POLYMED", "Poly Medicure Ltd."),
    ("PPLPHARMA", "Piramal Pharma Ltd."),
    ("RAINBOW", "Rainbow Childrens Medicare Ltd."),
    ("SAILIFE", "Sai Life Sciences Ltd."),
    ("SUNPHARMA", "Sun Pharmaceutical Industries Ltd."),
    ("SYNGENE", "Syngene International Ltd."),
    ("TORNTPHARM", "Torrent Pharmaceuticals Ltd."),
    ("VIJAYA", "Vijaya Diagnostic Centre Ltd."),
    ("WOCKPHARMA", "Wockhardt Ltd."),
    ("ZYDUSLIFE", "Zydus Lifesciences Ltd."),
    # ──────────────────── INFORMATION TECHNOLOGY (27) ────────────────────
    ("AFFLE", "Affle 3i Ltd."),
    ("BSOFT", "Birlasoft Ltd."),
    ("COFORGE", "Coforge Ltd."),
    ("CYIENT", "Cyient Ltd."),
    ("HCLTECH", "HCL Technologies Ltd."),
    ("HEXT", "Hexaware Technologies Ltd."),
    ("IKS", "Inventurus Knowledge Solutions Ltd."),
    ("INFY", "Infosys Ltd."),
    ("INTELLECT", "Intellect Design Arena Ltd."),
    ("KPITTECH", "KPIT Technologies Ltd."),
    ("LATENTVIEW", "Latent View Analytics Ltd."),
    ("LTM", "LTM Ltd."),
    ("LTTS", "L&T Technology Services Ltd."),
    ("MAPMYINDIA", "C.E. Info Systems Ltd."),
    ("MPHASIS", "MphasiS Ltd."),
    ("NETWEB", "Netweb Technologies India Ltd."),
    ("NEWGEN", "Newgen Software Technologies Ltd."),
    ("OFSS", "Oracle Financial Services Software Ltd."),
    ("PERSISTENT", "Persistent Systems Ltd."),
    ("SAGILITY", "Sagility Ltd."),
    ("SONATSOFTW", "Sonata Software Ltd."),
    ("TATAELXSI", "Tata Elxsi Ltd."),
    ("TATATECH", "Tata Technologies Ltd."),
    ("TCS", "Tata Consultancy Services Ltd."),
    ("TECHM", "Tech Mahindra Ltd."),
    ("WIPRO", "Wipro Ltd."),
    ("ZENSARTECH", "Zensar Technolgies Ltd."),
    # ──────────────────── MEDIA ENTERTAINMENT & PUBLICATION (5) ────────────────────
    ("PFOCUS", "Prime Focus Ltd."),
    ("PVRINOX", "PVR INOX Ltd."),
    ("SAREGAMA", "Saregama India Ltd"),
    ("SUNTV", "Sun TV Network Ltd."),
    ("ZEEL", "Zee Entertainment Enterprises Ltd."),
    # ──────────────────── METALS & MINING (18) ────────────────────
    ("ADANIENT", "Adani Enterprises Ltd."),
    ("GMDCLTD", "Gujarat Mineral Development Corporation Ltd."),
    ("GRAVITA", "Gravita India Ltd."),
    ("HINDALCO", "Hindalco Industries Ltd."),
    ("HINDCOPPER", "Hindustan Copper Ltd."),
    ("HINDZINC", "Hindustan Zinc Ltd."),
    ("JAINREC", "Jain Resource Recycling Ltd."),
    ("JINDALSTEL", "Jindal Steel Ltd."),
    ("JSL", "Jindal Stainless Ltd."),
    ("JSWSTEEL", "JSW Steel Ltd."),
    ("LLOYDSME", "Lloyds Metals And Energy Ltd."),
    ("NATIONALUM", "National Aluminium Co. Ltd."),
    ("NMDC", "NMDC Ltd."),
    ("NSLNISP", "NMDC Steel Ltd."),
    ("SAIL", "Steel Authority of India Ltd."),
    ("SARDAEN", "Sarda Energy and Minerals Ltd."),
    ("TATASTEEL", "Tata Steel Ltd."),
    ("VEDL", "Vedanta Ltd."),
    # ──────────────────── OIL GAS & CONSUMABLE FUELS (17) ────────────────────
    ("AEGISLOG", "Aegis Logistics Ltd."),
    ("AEGISVOPAK", "Aegis Vopak Terminals Ltd."),
    ("ATGL", "Adani Total Gas Ltd."),
    ("BPCL", "Bharat Petroleum Corporation Ltd."),
    ("CASTROLIND", "Castrol India Ltd."),
    ("CHENNPETRO", "Chennai Petroleum Corporation Ltd."),
    ("COALINDIA", "Coal India Ltd."),
    ("GAIL", "GAIL (India) Ltd."),
    ("HINDPETRO", "Hindustan Petroleum Corporation Ltd."),
    ("IGL", "Indraprastha Gas Ltd."),
    ("IOC", "Indian Oil Corporation Ltd."),
    ("MGL", "Mahanagar Gas Ltd."),
    ("MRPL", "Mangalore Refinery & Petrochemicals Ltd."),
    ("OIL", "Oil India Ltd."),
    ("ONGC", "Oil & Natural Gas Corporation Ltd."),
    ("PETRONET", "Petronet LNG Ltd."),
    ("RELIANCE", "Reliance Industries Ltd."),
    # ──────────────────── POWER (17) ────────────────────
    ("ACMESOLAR", "ACME Solar Holdings Ltd."),
    ("ADANIENSOL", "Adani Energy Solutions Ltd."),
    ("ADANIGREEN", "Adani Green Energy Ltd."),
    ("ADANIPOWER", "Adani Power Ltd."),
    ("CESC", "CESC Ltd."),
    ("JPPOWER", "Jaiprakash Power Ventures Ltd."),
    ("JSWENERGY", "JSW Energy Ltd."),
    ("NAVA", "Nava Ltd."),
    ("NHPC", "NHPC Ltd."),
    ("NLCINDIA", "NLC India Ltd."),
    ("NTPC", "NTPC Ltd."),
    ("NTPCGREEN", "NTPC Green Energy Ltd."),
    ("POWERGRID", "Power Grid Corporation of India Ltd."),
    ("RPOWER", "Reliance Power Ltd."),
    ("SJVN", "SJVN Ltd."),
    ("TATAPOWER", "Tata Power Co. Ltd."),
    ("TORNTPOWER", "Torrent Power Ltd."),
    # ──────────────────── REALTY (11) ────────────────────
    ("ABREL", "Aditya Birla Real Estate Ltd."),
    ("ANANTRAJ", "Anant Raj Ltd."),
    ("BRIGADE", "Brigade Enterprises Ltd."),
    ("DLF", "DLF Ltd."),
    ("GODREJPROP", "Godrej Properties Ltd."),
    ("LODHA", "Lodha Developers Ltd."),
    ("OBEROIRLTY", "Oberoi Realty Ltd."),
    ("PHOENIXLTD", "Phoenix Mills Ltd."),
    ("PRESTIGE", "Prestige Estates Projects Ltd."),
    ("SIGNATURE", "Signatureglobal (India) Ltd."),
    ("SOBHA", "Sobha Ltd."),
    # ──────────────────── SERVICES (14) ────────────────────
    ("ADANIPORTS", "Adani Ports and Special Economic Zone Ltd."),
    ("BLUEDART", "Blue Dart Express Ltd."),
    ("CONCOR", "Container Corporation of India Ltd."),
    ("DELHIVERY", "Delhivery Ltd."),
    ("ECLERX", "eClerx Services Ltd."),
    ("FSL", "Firstsource Solutions Ltd."),
    ("GESHIP", "Great Eastern Shipping Co. Ltd."),
    ("GMRAIRPORT", "GMR Airports Ltd."),
    ("IGIL", "International Gemological Institute Ltd."),
    ("INDIGO", "InterGlobe Aviation Ltd."),
    ("JSWINFRA", "JSW Infrastructure Ltd."),
    ("MMTC", "MMTC Ltd."),
    ("REDINGTON", "Redington Ltd."),
    ("SCI", "Shipping Corporation of India Ltd."),
    # ──────────────────── TELECOMMUNICATION (10) ────────────────────
    ("BHARTIARTL", "Bharti Airtel Ltd."),
    ("BHARTIHEXA", "Bharti Hexacom Ltd."),
    ("HFCL", "HFCL Ltd."),
    ("IDEA", "Vodafone Idea Ltd."),
    ("INDUSTOWER", "Indus Towers Ltd."),
    ("ITI", "ITI Ltd."),
    ("RAILTEL", "Railtel Corporation Of India Ltd."),
    ("TATACOMM", "Tata Communications Ltd."),
    ("TEJASNET", "Tejas Networks Ltd."),
    ("TTML", "Tata Teleservices (Maharashtra) Ltd."),
    # ──────────────────── TEXTILES (5) ────────────────────
    ("KPRMILL", "K.P.R. Mill Ltd."),
    ("PAGEIND", "Page Industries Ltd."),
    ("TRIDENT", "Trident Ltd."),
    ("VTL", "Vardhman Textiles Ltd."),
    ("WELSPUNLIV", "Welspun Living Ltd."),
]

assert len(STOCK_UNIVERSE) == 500, f"Expected 500 stocks, found {len(STOCK_UNIVERSE)}"

_SYMBOL_MAP: Dict[str, str] = {sym.upper(): name for sym, name in STOCK_UNIVERSE}


def get_universe() -> List[Tuple[str, str]]:
    """Return the full tuple list of (symbol, company_name) for all 500 constituents."""
    return list(STOCK_UNIVERSE)


def get_symbols() -> List[str]:
    """Return list of all 500 uppercase NSE ticker symbols."""
    return [sym for sym, _ in STOCK_UNIVERSE]


def get_symbol_name_map() -> Dict[str, str]:
    """Return dictionary mapping uppercase NSE ticker to official registered company name."""
    return dict(_SYMBOL_MAP)


def get_company_name(symbol: str) -> str:
    """Resolve official company name from symbol, with fallback to uppercase symbol."""
    clean = symbol.upper().replace(".NS", "").replace(".BO", "")
    return _SYMBOL_MAP.get(clean, clean)


if __name__ == "__main__":
    print(f"[Stock Universe] Loaded {len(STOCK_UNIVERSE)} official Nifty 500 constituents across 20 industries.")
    print(f"  First: {STOCK_UNIVERSE[0]}")
    print(f"  Last:  {STOCK_UNIVERSE[-1]}")
